---
title: "Adding the speed observations to the graph object"
date: "Created: 05-07-2024. Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    # df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
always_allow_html: true
---

```{r, eval = FALSE, echo = FALSE}
################################################################################
################################################################################
################################################################################
################################################################################
######### DO NOT FORGET TO CHANGE THE TITLE EVERY TIME YOU FIT A MODEL #########
################################################################################
################################################################################
################################################################################
################################################################################
```

```{r xaringanExtra-clipboard, echo = FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa-solid fa-clipboard\" style=\"color: #00008B\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times-circle\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```


```{css, echo = FALSE}
body .main-container {
  max-width: 100% !important;
  width: 100% !important;
}
body {
  max-width: 100% !important;
}

body, td {
   font-size: 16px;
}
code.r{
  font-size: 14px;
}
pre {
  font-size: 14px
}
```

Go back to the [Preprocessing page](../preprocessing.html). This [link](../data_files/README.html) might be useful to keep track of the files created during the preprocessing.

Let us set some global options for all code chunks in this document.

```{r}
knitr::opts_chunk$set(
  message = FALSE,    # Disable messages printed by R code chunks
  warning = FALSE,    # Disable warnings printed by R code chunks
  echo = TRUE,        # Show R code within code chunks in output
  include = TRUE,     # Include both R code and its results in output
  eval = TRUE,       # Evaluate R code chunks
  cache = FALSE,       # Enable caching of R code chunks for faster rendering
  fig.align = "center",
  out.width = "100%",
  retina = 2,
  error = TRUE,
  collapse = FALSE
)
rm(list = ls())
set.seed(1982)
```

# Import libraries

```{r}
# Install R-INLA package
# install.packages("INLA",repos = c(getOption("repos"),INLA ="https://inla.r-inla-download.org/R/testing"), dep = TRUE)
# Update R-INLA package
# inla.upgrade(testing = TRUE)
# Install inlabru package
# remotes::install_github("inlabru-org/inlabru", ref = "devel")
# Install rSPDE package
# remotes::install_github("davidbolin/rspde", ref = "devel")
# Install MetricGraph package
# remotes::install_github("davidbolin/metricgraph", ref = "devel")

library(INLA)
library(inlabru)
library(rSPDE)
library(MetricGraph)

library(plotly)
library(dplyr)
library(tidyr)
library(sf)
library(mapview)
library(listviewer)
library(jsonlite)
library(ggplot2)

library(here) # here() starts from the home directory
library(rmarkdown)

rm(list = ls()) # Clear the workspace
set.seed(1982) # Set seed for reproducibility
```

# Load the graph and data

```{r}
# Load the graph
load(here("data_files/graph_construction_on_27JUN2024_FRC013456.RData"))
# Load the data
load(here("data_files/day7142128hour13noconsecutivezeroes.RData"))
```

## Explore the data

```{r}
df |> head(5) |> paged_table()
df |> dim()
```


```{r, fig.height=16}
# Plot using ggplot
ggplot(df) +
  geom_sf(aes(color = speed)) +
  facet_wrap(~day, ncol = 1) +
  theme_minimal() +
  labs(title = "Speed by Day", color = "Speed") +
  theme(plot.title = element_text(hjust = 0.5))
```

# Add the speed observations to the graph   

```{r, eval = FALSE}
# Build polygon to cut the network and the data
polygon <- st_multipoint(c(st_point(c(-122.53000, 37.69702)),
                          st_point(c(-122.37000, 37.69702)),
                          st_point(c(-122.37000, 37.82600)),
                          st_point(c(-122.53000, 37.82600)))) %>%
  st_cast("POLYGON") %>%
  st_sfc(crs = st_crs(df)) # df dataset needs to be loaded to get the crs

# Filter the data to get only the data within the polygon
data.reduced <- st_filter(x = df, y = polygon, .predicate = st_within)

# Add the observations to the graph
sf_graph$add_observations(data = data.reduced, group = "day", tolerance = 0.02, duplicated_strategy = "jitter") # tolerance = 20m

# Get the data from the graph (that is, in graph coordinates)
data_on_graph <- sf_graph$get_data()

# Save the graph-processed data
save(data_on_graph, file = here("data_files/data_day7142128_hour13_with_no_consecutive_zeros_27JUN2024_FRC013456_graph_processed.RData"))
```

## Explore the data

```{r, include = FALSE}
# Load the graph-processed data
load(here("data_files/data_day7142128_hour13_with_no_consecutive_zeros_27JUN2024_FRC013456_graph_processed.RData"))
```

```{r}
data_on_graph |> head(5) |> paged_table()
data_on_graph |> dim()
```

```{r, fig.height=16}
# Plot using ggplot
ggplot(data_on_graph) +
  geom_point(aes(x = .coord_x, y = .coord_y, color = speed)) +
  facet_wrap(~day, ncol = 1) +
  theme_minimal() +
  labs(title = "Speed by Day", color = "Speed") +
  theme(plot.title = element_text(hjust = 0.5))
```

