---
title: "Contents of This Website"
---

1. PeMS Data

    - [PeMS 1](pems_repl1.html)
    - [PeMS 2](pems_repl2.html)

2. Model Properties

    - [Model Properties 1](model_properties1.html)
    - [Model Properties 2](model_properties2.html)
    - [Model Properties 3](marginal_sd.html)
    - [Model Properties 4](tau_effect.html)

3. Basis Functions

    - [Basis Functions](basis_functions.html)
    - [Functions on graphs](functions_on_graph.html)
    - [Alternative Illustrations](basis_functions_alt_illustrations.html)

4. Approximation

    - [Approximation](approximation.html)
    - [Approximation using KL expansion](approximation_kl.html)

5. Numerical Error

    - [Numerical Error](numerical_error.html)

6. Convergence Rates

    - [Convergence Rates](convergence_rates.html)
    - [More details for interval graph](convergence_rates/convergence_rates_interval.html)
    - [More details for circle graph](convergence_rates/convergence_rates_circle.html)
    - [More details for tadpole graph](convergence_rates/convergence_rates_tadpole.html)
