---
title: "Interval, Circle, and Tadpole graphs"
date: "Created: 05-07-2024. Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    # df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
---

```{r, eval = FALSE, echo = FALSE}
################################################################################
################################################################################
################################################################################
################################################################################
######### DO NOT FORGET TO CHANGE THE TITLE EVERY TIME YOU FIT A MODEL #########
################################################################################
################################################################################
################################################################################
################################################################################
```

```{r xaringanExtra-clipboard, echo = FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa-solid fa-clipboard\" style=\"color: #00008B\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times-circle\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```


```{css, echo = FALSE}
body .main-container {
  max-width: 100% !important;
  width: 100% !important;
}
body {
  max-width: 100% !important;
}

body, td {
   font-size: 16px;
}
code.r{
  font-size: 14px;
}
pre {
  font-size: 14px
}
```


Go back to the [About page](about.html).

Let us set some global options for all code chunks in this document.


```{r}
knitr::opts_chunk$set(
  message = FALSE,    # Disable messages printed by R code chunks
  warning = FALSE,    # Disable warnings printed by R code chunks
  echo = TRUE,        # Show R code within code chunks in output
  include = TRUE,     # Include both R code and its results in output
  eval = TRUE,       # Evaluate R code chunks
  cache = FALSE,       # Enable caching of R code chunks for faster rendering
  fig.align = "center",
  out.width = "100%",
  retina = 2,
  error = TRUE,
  collapse = FALSE
)
rm(list = ls())
set.seed(1982)
```

# Import libraries

```{r}
library(MetricGraph)
library(Matrix)
library(rSPDE)

library(dplyr)
library(tidyverse)
library(plotly)

library(grateful) # Cite all loaded packages

rm(list = ls()) # Clear the workspace
set.seed(1982) # Set seed for reproducibility
```


# Interval graph

```{r, out.width= "50%"}
# Function to build an interval graph and create a mesh
gets_graph_interval <- function(n){
  edge <- rbind(c(0,0),c(1,0))
  edges = list(edge)
  graph <- metric_graph$new(edges = edges)
  graph$build_mesh(n = n)
  return(graph)
}

# Plot the interval graph
gets_graph_interval(n = 333)$plot() +
  ggtitle("Interval graph") + 
  theme_minimal() + 
  theme(text = element_text(family = "Palatino"))
```


<div style="color: blue;">
********
**Press the Show button below to reveal the code.**

********
</div>


```{r, class.source = "fold-hide"}
# Matern covariance function
matern.covariance <- function(h, kappa, nu, sigma) {
  if (nu == 1 / 2) {
    C <- sigma^2 * exp(-kappa * abs(h))
  } else {
    C <- (sigma^2 / (2^(nu - 1) * gamma(nu))) *
      ((kappa * abs(h))^nu) * besselK(kappa * abs(h), nu)
  }
  C[h == 0] <- sigma^2
  return(as.matrix(C))
}

# Folded.matern.covariance.1d
folded.matern.covariance.1d.local <- function(x, kappa, nu, sigma,
                                              L = 1, N = 10,
                                              boundary = c("neumann",
                                                           "dirichlet", "periodic")) {
  boundary <- tolower(boundary[1])
  if (!(boundary %in% c("neumann", "dirichlet", "periodic"))) {
    stop("The possible boundary conditions are 'neumann',
    'dirichlet' or 'periodic'!")
  }
  addi = t(outer(x, x, "+"))
  diff = t(outer(x, x, "-"))
  s1 <- sapply(-N:N, function(j) { 
    diff + 2 * j * L
  })
  s2 <- sapply(-N:N, function(j) {
    addi + 2 * j * L
  })
  if (boundary == "neumann") {
    C <- rowSums(matern.covariance(h = s1, kappa = kappa,
                                   nu = nu, sigma = sigma) +
                   matern.covariance(h = s2, kappa = kappa,
                                     nu = nu, sigma = sigma))
  } else if (boundary == "dirichlet") {
    C <- rowSums(matern.covariance(h = s1, kappa = kappa,
                                   nu = nu, sigma = sigma) -
                   matern.covariance(h = s2, kappa = kappa,
                                     nu = nu, sigma = sigma))
  } else {
    C <- rowSums(matern.covariance(h = s1,
                                   kappa = kappa, nu = nu, sigma = sigma))
  }
  return(matrix(C, nrow = length(x)))
}

# Function to get the true covariance matrix
gets_true_cov_mat = function(graph, kappa, nu, sigma, N, boundary){
  #h = c(graph$mesh$V[-2,1], graph$mesh$V[2,1])
  h = graph$mesh$V[,1]
  true_cov_mat = folded.matern.covariance.1d.local(x = h, kappa = kappa, nu = nu, sigma = sigma, N = N, boundary = boundary)
  return(true_cov_mat)
}


# Parameters of the approximation
n = 333
type = "covariance"
type_rational_approximation = "chebfun"
rho = 1
m = 4
nu = 0.6
sigma = 1
N.folded = 10
boundary = "neumann"

# Get the graph and build the mesh
graph = gets_graph_interval(n = n)

kappa = sqrt(8*nu)/rho
tau = sqrt(gamma(nu) / (sigma^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))  #sigma = 1, d = 1
alpha = nu + 1/2

# Get the true covariance
true_cov_mat = gets_true_cov_mat(graph = graph,
                                 kappa = kappa,
                                 nu = nu,
                                 sigma = sigma,
                                 N = N.folded,
                                 boundary = boundary)

# Get the approximate covariance matrix
op = matern.operators(alpha = alpha, 
                      kappa = kappa, 
                      tau = tau,
                      m = m, 
                      graph = graph,
                      type = type,
                      type_rational_approximation = type_rational_approximation)

appr_cov_mat = op$covariance_mesh()

# Plot the true covariance and the approximation
point  <- c(1,0.5)
c_cov <- op$cov_function_mesh(matrix(point,1,2))
loc <- graph$coordinates(PtE = point)
m1 <- which.min((graph$mesh$V[,1]-loc[1])^2 + (graph$mesh$V[,2]-loc[2])^2)
p = graph$plot_function(true_cov_mat[m1,], plotly = TRUE, line_width = 3, edge_width = 3) # blue is the true one
graph$plot_function(c_cov,p=p, line_color = "red", plotly = TRUE,line_width = 3, edge_width = 3)  %>% 
  config(mathjax = 'cdn') %>% 
  layout(font = list(family = "Palatino"),
         scene = list(
           annotations = list(
             list(
               x = 0, y = 0, z = 0,
               text = TeX("v_1"),
               textangle = 0, ax = 0, ay = 15,
               font = list(color = "black", size = 16),
               arrowcolor = "black", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1),
             list(
               x = 0, y = 1, z = 0,
               text = TeX("v_2"),
               textangle = 0, ax = 0, ay = 15,
               font = list(color = "black", size = 16),
               arrowcolor = "black", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1),
             list(
               x = 0, y = 0.5, z = 0,
               text = TeX("e_1"),
               textangle = 0, ax = 0, ay = 15,
               font = list(color = "black", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1),
             list(
               x = 0, y = 0.6, z = 1.25,
               text = TeX("\\bullet\\mbox{ exact}"),
               textangle = 0, ax = 60, ay = 0,
               font = list(color = "blue", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1),
             list(
               x = 0, y = 0.745, z = 1.20,
               text = TeX("\\bullet\\mbox{ approximated}"),
               textangle = 0, ax = 60, ay = 0,
               font = list(color = "red", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1))))
```


```{r}
# Compute the errors
L_inf_error = max(abs(true_cov_mat - appr_cov_mat))
L_2_error = sqrt(as.double(t(graph$mesh$weights)%*%(true_cov_mat - appr_cov_mat)^2%*%graph$mesh$weights))
print(L_inf_error)
print(L_2_error)
```


# Circle graph

```{r, out.width= "50%"}
# Function to build a circle graph and create a mesh
gets_graph_circle <- function(n){
  r = 1/(pi)
  theta <- seq(from=-pi,to=pi,length.out = 100)
  edge <- cbind(1+r+r*cos(theta),r*sin(theta))
  edges = list(edge)
  graph <- metric_graph$new(edges = edges)
  graph$build_mesh(n = n)
  return(graph)
}

# Plot the circle graph
gets_graph_circle(n = 666)$plot() +
  ggtitle("Circle graph") + 
  theme_minimal() + 
  theme(text = element_text(family = "Palatino"))
```


<div style="color: blue;">
********
**Press the Show button below to reveal the code.**

********
</div>


```{r, class.source = "fold-hide"}
# Matern covariance function
matern.covariance <- function(h, kappa, nu, sigma) {
  if (nu == 1 / 2) {
    C <- sigma^2 * exp(-kappa * abs(h))
  } else {
    C <- (sigma^2 / (2^(nu - 1) * gamma(nu))) *
      ((kappa * abs(h))^nu) * besselK(kappa * abs(h), nu)
  }
  C[h == 0] <- sigma^2
  return(as.matrix(C))
}

# Folded.matern.covariance.1d 
folded.matern.covariance.1d.local <- function(x, kappa, nu, sigma, L = 1, N = 10, boundary = c("neumann",
                                                           "dirichlet", "periodic")) {
  boundary <- tolower(boundary[1])
  if (!(boundary %in% c("neumann", "dirichlet", "periodic"))) {
    stop("The possible boundary conditions are 'neumann',
    'dirichlet' or 'periodic'!")
  }
  addi = t(outer(x, x, "+"))
  diff = t(outer(x, x, "-"))
  s1 <- sapply(-N:N, function(j) { # s1 is a matrix of size length(h)x(2N+1)
    diff + 2 * j * L
  })
  s2 <- sapply(-N:N, function(j) {
    addi + 2 * j * L
  })
  if (boundary == "neumann") {
    C <- rowSums(matern.covariance(h = s1, kappa = kappa,
                                   nu = nu, sigma = sigma) +
                   matern.covariance(h = s2, kappa = kappa,
                                     nu = nu, sigma = sigma))
  } else if (boundary == "dirichlet") {
    C <- rowSums(matern.covariance(h = s1, kappa = kappa,
                                   nu = nu, sigma = sigma) -
                   matern.covariance(h = s2, kappa = kappa,
                                     nu = nu, sigma = sigma))
  } else {
    C <- rowSums(matern.covariance(h = s1,
                                   kappa = kappa, nu = nu, sigma = sigma))
  }
  return(matrix(C, nrow = length(x)))
}

# Function to get the true covariance matrix
gets_true_cov_mat = function(graph, kappa, nu, sigma, N, boundary){
  h = c(0,graph$get_edge_lengths()[1]*graph$mesh$PtE[,2])
  true_cov_mat = folded.matern.covariance.1d.local(x = h, kappa = kappa, nu = nu, sigma = sigma, N = N, boundary = boundary)
  return(true_cov_mat)
}


# Parameters of the approximation
n = 666
type = "covariance"
type_rational_approximation = "chebfun"
rho = 1
m = 4
nu = 0.6
sigma = 1
N.folded = 10
boundary = "periodic"

# Get the graph and build the mesh
graph = gets_graph_circle(n = n)


kappa = sqrt(8*nu)/rho
tau = sqrt(gamma(nu) / (sigma^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))  #sigma = 1, d = 1
alpha = nu + 1/2

# Get the "true" covariance matrix
true_cov_mat = gets_true_cov_mat(graph = graph,
                                 kappa = kappa,
                                 nu = nu,
                                 sigma = sigma,
                                 N = N.folded,
                                 boundary = boundary)

# Get the approximate covariance matrix
op = matern.operators(alpha = alpha, 
                      kappa = kappa, 
                      tau = tau,
                      m = m, 
                      graph = graph,
                      type = type,
                      type_rational_approximation = type_rational_approximation)
appr_cov_mat = op$covariance_mesh()

# Plot the true covariance and the approximation
point  <- c(1,0)
c_cov <- op$cov_function_mesh(matrix(point,1,2))
loc <- graph$coordinates(PtE = point)
m1 <- which.min((graph$mesh$V[,1]-loc[1])^2 + (graph$mesh$V[,2]-loc[2])^2)
p = graph$plot_function(true_cov_mat[m1,], plotly = TRUE, line_width = 3, edge_width = 3)
graph$plot_function(c_cov,p=p, line_color = "red", plotly = TRUE,line_width = 3, edge_width = 3) %>% 
  config(mathjax = 'cdn') %>% 
  layout(font = list(family = "Palatino"),
         scene = list(
           annotations = list(
             list(
               x = -0.03, y = 1.03, z = 0,
               text = TeX("v_1"),
               textangle = 0, ax = 0, ay = 15,
               font = list(color = "black", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1),
             list(
               x = 0.26, y = 1.54, z = 0,
               text = TeX("e_1"),
               textangle = 0, ax = 0, ay = 15,
               font = list(color = "black", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1),
             list(
               x = -0.05, y = 1.085, z = 0.95,
               text = TeX("\\bullet\\mbox{ exact}"),
               textangle = 0, ax = 60, ay = 0,
               font = list(color = "blue", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1),
             list(
               x = -0.05, y = 1.2, z = 0.9,
               text = TeX("\\bullet\\mbox{ approximated}"),
               textangle = 0, ax = 60, ay = 0,
               font = list(color = "red", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1))))
```


```{r}
# Compute the errors
L_inf_error = max(abs(true_cov_mat - appr_cov_mat))
L_2_error = sqrt(as.double(t(graph$mesh$weights)%*%(true_cov_mat - appr_cov_mat)^2%*%graph$mesh$weights))
print(L_inf_error)
print(L_2_error)
```

# Tadpole graph

```{r, out.width= "50%"}
# Function to build a tadpole graph and create a mesh
gets_graph_tadpole <- function(h){
  edge1 <- rbind(c(0,0),c(1,0))
  theta <- seq(from=-pi,to=pi,length.out = 100)
  edge2 <- cbind(1+1/pi+cos(theta)/pi,sin(theta)/pi)
  edges = list(edge1, edge2)
  graph <- metric_graph$new(edges = edges)
  graph$build_mesh(h = h)
  return(graph)
}
# Plot the tadpole graph
gets_graph_tadpole(h = 0.003)$plot() +
  ggtitle("Tadpole graph") + 
  theme_minimal() + 
  theme(text = element_text(family = "Palatino"))
```


<div style="color: blue;">
********
**Press the Show button below to reveal the code.**

********
</div>


```{r, class.source = "fold-hide"}
# Function to compute the eigenfunctions 
tadpole.eig <- function(k,graph){
x1 <- c(0,graph$get_edge_lengths()[1]*graph$mesh$PtE[graph$mesh$PtE[,1]==1,2]) 
x2 <- c(0,graph$get_edge_lengths()[2]*graph$mesh$PtE[graph$mesh$PtE[,1]==2,2]) 

if(k==0){ 
  f.e1 <- rep(1,length(x1)) 
  f.e2 <- rep(1,length(x2)) 
  f1 = c(f.e1[1],f.e2[1],f.e1[-1], f.e2[-1]) 
  f = list(phi=f1/sqrt(3)) 
  
} else {
  f.e1 <- -2*sin(pi*k*1/2)*cos(pi*k*x1/2) 
  f.e2 <- sin(pi*k*x2/2)                  
  
  f1 = c(f.e1[1],f.e2[1],f.e1[-1], f.e2[-1]) 
  
  if((k %% 2)==1){ 
    f = list(phi=f1/sqrt(3)) 
  } else { 
    f.e1 <- (-1)^{k/2}*cos(pi*k*x1/2)
    f.e2 <- cos(pi*k*x2/2)
    f2 = c(f.e1[1],f.e2[1],f.e1[-1],f.e2[-1]) 
    f <- list(phi=f1,psi=f2/sqrt(3/2))
  }
}

return(f)
}

# Function to get the true covariance matrix
gets_true_cov_mat <- function(graph, kappa, tau, alpha, n.overkill){
  Sigma.kl <- matrix(0,nrow = dim(graph$mesh$V)[1],ncol = dim(graph$mesh$V)[1])
  for(i in 0:n.overkill){
    phi <- tadpole.eig(i,graph)$phi
    Sigma.kl <- Sigma.kl + (1/(kappa^2 + (i*pi/2)^2)^(alpha))*phi%*%t(phi)
    if(i>0 && (i %% 2)==0){ 
      psi <- tadpole.eig(i,graph)$psi
      Sigma.kl <- Sigma.kl + (1/(kappa^2 + (i*pi/2)^2)^(alpha))*psi%*%t(psi)
    }
    
  }
  Sigma.kl <- Sigma.kl/tau^2
  return(Sigma.kl)
}

# Parameters of the approximation
h = 0.003
type = "covariance"
type_rational_approximation = "chebfun"
rho = 1
m = 4
nu = 0.6

# Get the graph and build the mesh
graph = gets_graph_tadpole(h = h)


n.overkill = 10000
kappa = sqrt(8*nu)/rho
tau = sqrt(gamma(nu) / (1^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))  #sigma = 1, d = 1
alpha = nu + 1/2


# Get the true covariance
true_cov_mat = gets_true_cov_mat(graph = graph,
                                 kappa = kappa,
                                 tau = tau,
                                 alpha = alpha,
                                 n.overkill = n.overkill)

# Get the approximate covariance matrix
op = matern.operators(alpha = alpha, 
                      kappa = kappa, 
                      tau = tau,
                      m = m, 
                      graph = graph,
                      type = type,
                      type_rational_approximation = type_rational_approximation)

appr_cov_mat = op$covariance_mesh()


# Plot the true covariance and the approximation
point  <- c(1,1)
c_cov <- op$cov_function_mesh(matrix(point,1,2))
loc <- graph$coordinates(PtE = point)
m1 <- which.min((graph$mesh$V[,1]-loc[1])^2 + (graph$mesh$V[,2]-loc[2])^2)
p <- graph$plot_function(true_cov_mat[m1,], plotly = TRUE, line_width = 3, edge_width = 3) # blue is the true one
graph$plot_function(c_cov,p=p, line_color = "red", plotly = TRUE,line_width = 3, edge_width = 3) %>% 
  config(mathjax = 'cdn') %>% 
  layout(font = list(family = "Palatino"),
         scene = list(
           annotations = list(
             list(
               x = 0, y = 0, z = 0,
               text = TeX("v_1"),
               textangle = 0, ax = 0, ay = 15,
               font = list(color = "black", size = 16),
               arrowcolor = "black", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1),
             list(
               x = -0.03, y = 1.03, z = 0,
               text = TeX("v_2"),
               textangle = 0, ax = 0, ay = 15,
               font = list(color = "black", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1),
             list(
               x = 0, y = 0.5, z = 0,
               text = TeX("e_1"),
               textangle = 0, ax = 0, ay = 15,
               font = list(color = "black", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 0),
             list(
               x = 0.26, y = 1.54, z = 0,
               text = TeX("e_2"),
               textangle = 0, ax = 0, ay = 15,
               font = list(color = "black", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1),
             list(
               x = -0.08, y = 1.135, z = 0.65,
               text = TeX("\\bullet\\mbox{ exact}"),
               textangle = 0, ax = 60, ay = 0,
               font = list(color = "blue", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1),
             list(
               x = -0.08, y = 1.25, z = 0.6,
               text = TeX("\\bullet\\mbox{ approximated}"),
               textangle = 0, ax = 60, ay = 0,
               font = list(color = "red", size = 16),
               arrowcolor = "white", arrowsize = 1, arrowwidth = 0.1,arrowhead = 1))))
```


```{r}
# Compute the errors
L_inf_error = max(abs(true_cov_mat - appr_cov_mat))
L_2_error = sqrt(as.double(t(graph$mesh$weights)%*%(true_cov_mat - appr_cov_mat)^2%*%graph$mesh$weights))
print(L_inf_error)
print(L_2_error)
```


# References

```{r}
cite_packages(output = "paragraph", out.dir = ".")
```
