---
title: "Using the KL expansion to approximate the covariance matrix for the interval and circle cases"
date: "Created: 05-07-2024. Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    # df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
---

```{r, eval = FALSE, echo = FALSE}
################################################################################
################################################################################
################################################################################
################################################################################
######### DO NOT FORGET TO CHANGE THE TITLE EVERY TIME YOU FIT A MODEL #########
################################################################################
################################################################################
################################################################################
################################################################################
```

```{r xaringanExtra-clipboard, echo = FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa-solid fa-clipboard\" style=\"color: #00008B\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times-circle\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```


```{css, echo = FALSE}
body .main-container {
  max-width: 100% !important;
  width: 100% !important;
}
body {
  max-width: 100% !important;
}

body, td {
   font-size: 16px;
}
code.r{
  font-size: 14px;
}
pre {
  font-size: 14px
}
```


Go back to the [About page](about.html).

Go back to the [Approximation](approximation.html) page

Let us set some global options for all code chunks in this document.


```{r}
knitr::opts_chunk$set(
  message = FALSE,    # Disable messages printed by R code chunks
  warning = FALSE,    # Disable warnings printed by R code chunks
  echo = TRUE,        # Show R code within code chunks in output
  include = TRUE,     # Include both R code and its results in output
  eval = TRUE,       # Evaluate R code chunks
  cache = FALSE,       # Enable caching of R code chunks for faster rendering
  fig.align = "center",
  out.width = "100%",
  retina = 2,
  error = TRUE,
  collapse = FALSE
)
rm(list = ls())
set.seed(1982)
```

# Import libraries

```{r}
library(MetricGraph)
library(Matrix)
library(rSPDE)

library(dplyr)
library(tidyverse)
library(plotly)

library(grateful) # Cite all loaded packages

rm(list = ls()) # Clear the workspace
set.seed(1982) # Set seed for reproducibility
```


# Interval graph {#kl-expansion-interval}

```{r, out.width = "50%"}
# function 1
gets_graph_interval <- function(n){
  edge <- rbind(c(0,0),c(1,0))
  edges = list(edge)
  graph <- metric_graph$new(edges = edges)
  graph$build_mesh(n = n)
  return(graph)
}


# true eigenfunctions
interval.eig <- function(k,graph){
  x <- c(0,graph$get_edge_lengths()[1]*graph$mesh$PtE[,2],1)
  if(k==0){
    f.0 <- rep(1,length(x)) 
    f1 = c(f.0[1],f.0[length(f.0)], f.0[2:(length(f.0)-1)])
    f = list(phi=f1) 
  }else{
    f.c <- sqrt(2)*cos(pi*k*x) 
    f2 = c(f.c[1],f.c[length(f.c)], f.c[2:(length(f.c)-1)])
    f <- list(psi=f2)
  }
  return(f)
}

# parameters
n = 333
rho = 1
m = 4
nu = 0.6
sigma = 1
n.overkill = 1000
graph = gets_graph_interval(n = n)

kappa = sqrt(8*nu)/rho
tau = sqrt(gamma(nu) / (sigma^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))  #sigma = 1, d = 1
alpha = nu + 1/2

# getting true covariance matrix
true_cov_mat <- matrix(0,nrow = dim(graph$mesh$V)[1],ncol = dim(graph$mesh$V)[1])
for(i in 0:n.overkill){
  if(i==0){
    phi <- interval.eig(i,graph)$phi
    true_cov_mat <- true_cov_mat + (1/(kappa^2 + (i*pi)^2)^(alpha))*phi%*%t(phi)
  }else{
    psi <- interval.eig(i,graph)$psi
    true_cov_mat <- true_cov_mat + (1/(kappa^2 + (i*pi)^2)^(alpha))*psi%*%t(psi) 
  }
  
}
true_cov_mat <- true_cov_mat/tau^2
true_cov_mat_reordered <- true_cov_mat[c(1,3:(n+2),2), c(1,3:(n+2),2)] # needs reorder


# getting approximate matrix 
op <- matern.operators(alpha = alpha, kappa = kappa, tau = tau,
                       m = m, graph = graph)
appr_cov_mat = op$covariance_mesh()
appr_cov_mat_reordered <- appr_cov_mat[c(1,3:(n+2),2), c(1,3:(n+2),2)] # needs reorder

# computing the errors
L_inf_error = max(abs(true_cov_mat - appr_cov_mat))
L_2_error = sqrt(as.double(t(graph$mesh$weights)%*%(true_cov_mat - appr_cov_mat)^2%*%graph$mesh$weights))
print(L_inf_error)
print(L_2_error)

# plot just for confirmation
plot(true_cov_mat_reordered[round(n/2)+1,], type="l", col = "blue", lty = 2) #true
lines(appr_cov_mat_reordered[round(n/2)+1,], type = "l", col = "red", lty = 3) #approx
legend("topright", legend = c("true", "approx"), col = c("blue", "red"), lty = 1)
```


```{r}
point  <- c(1, 0.5)
c_cov <- op$cov_function_mesh(matrix(point,1,2))
loc <- graph$coordinates(PtE = point)
m1 <- which.min((graph$mesh$V[,1]-loc[1])^2 + (graph$mesh$V[,2]-loc[2])^2)
p <- graph$plot_function(true_cov_mat[m1,], plotly = TRUE, line_width = 3)
graph$plot_function(c_cov,p=p, line_color = "red", plotly = TRUE,line_width = 3)
```

# Circle graph {#kl-expansion-circle}

```{r, out.width = "50%"}
r = 1/(pi)
theta <- seq(from=-pi,to=pi,length.out = 100)
edge <- cbind(1+r+r*cos(theta),r*sin(theta))
edges = list(edge)

n = 666

graph <- metric_graph$new(edges = edges)
graph$build_mesh(n = n)

#true eigenfunctions
circle.eig <- function(k,graph,L){
  x <- c(0,graph$get_edge_lengths()[1]*graph$mesh$PtE[,2],2)
  if(k==0){
    f.0 <- rep(1,length(x)) 
    f.0 = f.0[-length(f.0)]
    f = list(phi=f.0/sqrt(L)) 
  }else{
    f.c <- sqrt(2/L)*cos(pi*k*x/L) 
    f.c = f.c[-length(f.c)]
    f.s <- sqrt(2/L)*sin(pi*k*x/L) 
    f.s = f.s[-length(f.s)]
    f <- list(phi=f.c,psi=f.s)
  }
  return(f)
}

rho = 1
m = 4
nu = 0.6
sigma = 1
kappa = sqrt(8*nu)/rho
tau = sqrt(gamma(nu) / (sigma^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))  #sigma = 1, d = 1
alpha = nu + 1/2

L = 1
#check KL expansion
true_cov_mat <- matrix(0,nrow = dim(graph$mesh$V)[1],ncol = dim(graph$mesh$V)[1])
for(i in 0:1000){
  if(i==0){
    phi <- circle.eig(i,graph,L)$phi
    true_cov_mat <- true_cov_mat + (1/(kappa^2 + (i*pi/L)^2)^(alpha))*phi%*%t(phi)
  }else{
    eigen <- circle.eig(i,graph,L)
    psi <- eigen$psi
    phi <- eigen$phi
    true_cov_mat <- true_cov_mat + (1/(kappa^2 + (i*pi/L)^2)^(alpha))*psi%*%t(psi) + 
                           (1/(kappa^2 + (i*pi/L)^2)^(alpha))*phi%*%t(phi)
  }
  
}
true_cov_mat <- true_cov_mat/tau^2/2

# getting approximate matrix 
op <- matern.operators(alpha = alpha, kappa = kappa, tau = tau,
                       m = m, graph = graph)
appr_cov_mat = op$covariance_mesh()

# computing the errors
L_inf_error = max(abs(true_cov_mat - appr_cov_mat))
L_2_error = sqrt(as.double(t(graph$mesh$weights)%*%(true_cov_mat - appr_cov_mat)^2%*%graph$mesh$weights))
print(L_inf_error)
print(L_2_error)

#plot just for confirmation
plot(true_cov_mat[round(n/2),], type="l", col = "blue", lty = 2) #true
lines(appr_cov_mat[round(n/2),], type = "l", col = "red", lty = 3) #approx
legend("topright", legend = c("true", "approx"), col = c("blue", "red"), lty = 1)

```


```{r}
point  <- c(1,0)
c_cov <- op$cov_function_mesh(matrix(point,1,2))
loc <- graph$coordinates(PtE = point)
m1 <- which.min((graph$mesh$V[,1]-loc[1])^2 + (graph$mesh$V[,2]-loc[2])^2)
p <- graph$plot_function(true_cov_mat[m1,], plotly = TRUE, line_width = 3)
graph$plot_function(c_cov,p=p, line_color = "red", plotly = TRUE,line_width = 3)
```



# References

```{r}
cite_packages(output = "paragraph", out.dir = ".")
```
