---
title: "Function to compute practical correlation range"
date: "Created: 05-07-2024. Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    # df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
---

```{r, eval = FALSE, echo = FALSE}
################################################################################
################################################################################
################################################################################
################################################################################
######### DO NOT FORGET TO CHANGE THE TITLE EVERY TIME YOU FIT A MODEL #########
################################################################################
################################################################################
################################################################################
################################################################################
```

```{r xaringanExtra-clipboard, echo = FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa-solid fa-clipboard\" style=\"color: #00008B\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times-circle\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```


```{css, echo = FALSE}
body .main-container {
  max-width: 100% !important;
  width: 100% !important;
}
body {
  max-width: 100% !important;
}

body, td {
   font-size: 16px;
}
code.r{
  font-size: 14px;
}
pre {
  font-size: 14px
}
```


Go back to the [About page](about.html).

Let us set some global options for all code chunks in this document.


```{r}
knitr::opts_chunk$set(
  message = FALSE,    # Disable messages printed by R code chunks
  warning = FALSE,    # Disable warnings printed by R code chunks
  echo = TRUE,        # Show R code within code chunks in output
  include = TRUE,     # Include both R code and its results in output
  eval = TRUE,       # Evaluate R code chunks
  cache = FALSE,       # Enable caching of R code chunks for faster rendering
  fig.align = "center",
  #out.width = "100%",
  retina = 2,
  error = TRUE,
  collapse = FALSE
)
rm(list = ls())
set.seed(1982)
```

# Import libraries

```{r}
library(INLA)
library(inlabru)
library(rSPDE)
library(MetricGraph)

library(dplyr)
library(plotly)
library(scales)
library(patchwork)
library(tidyr)

library(here)
library(rmarkdown)
library(grateful) # Cite all loaded packages

rm(list = ls()) # Clear the workspace
set.seed(1982) # Set seed for reproducibility
```


```{r}
edges <- logo_lines() # This is a function from MetricGraph package that returns a list of edges
logo_graph <- metric_graph$new(edges = edges) # Create a new graph object

#logo_graph$prune_vertices()
logo_graph$build_mesh(h = 0.05) # Build the mesh


# Set the parameters
sigma <- 0.1 # Standard deviation
range <- 10 # Range
nu <- 1.5 # Smoothness parameter
theta <- c(1, 1, -2.5, 2.5) # Log-regression coefficients
nu_ns <- 1.5 # Smoothness parameter for non-stationarity
cor_threshold <- 0.1 # Define correlation threshold
sigma.e <- 0.1 # Standard deviation of the error term

# Construct the approximation
op <- matern.operators(nu = nu, 
                       sigma = sigma,
                       range = range,  
                       parameterization = "matern",
                       graph = logo_graph)    

# Simulate the field
cov <- as.vector(simulate(op))

# Non-stationary parameters
B.sigma = cbind(0, 1, 0, cov, 0)
B.range = cbind(0, 0, 1, 0, cov)

# Construct the approximation 
ns_op <- rSPDE::spde.matern.operators(graph = logo_graph,
                                                parameterization = "matern",
                                                B.sigma = B.sigma,
                                                B.range = B.range,
                                                theta = theta,
                                                nu = nu_ns)

# Covariance matrix
est_cov_matrix <- ns_op$covariance_mesh()

# Precision matrix
Q <- precision(ns_op)

# Compute distance matrix on the mesh
logo_graph$compute_geodist_mesh()

# Get the distance matrix
dist_matrix <- logo_graph$mesh$geo_dist

# Initialize vector to store the practical correlation range
est_range = rep(NA, dim(est_cov_matrix)[1])
  
# Compute the practical correlation range
for (i in 1:dim(est_cov_matrix)[1]) {
  est_range[i] <- data.frame(cor = est_cov_matrix[i,], dist = dist_matrix[i,]) %>% 
    arrange(dist) %>% 
    filter(cor < cor_threshold) %>%
  slice(1) %>%
  pull(dist)
}

# Compute the standard deviation
est_sigma <- sqrt(diag(INLA::inla.qinv(Q))) # It can also be computed as sqrt(Matrix::diag(est_cov_matrix))
```

```{r}
compute_pcr <- function(op, cor_threshold) {
  
  cov_matrix <- op$covariance_mesh()
  op$graph$compute_geodist_mesh()
  dist_matrix <- op$graph$mesh$geo_dist
  pcr <- numeric(dim(cov_matrix)[1])
  
  process_row <- function(row_index) {
    df <- cbind(cov_matrix[row_index, ], dist_matrix[row_index, ])
    ordered_df <- df[order(df[, 2]), ]
    filtered_df <- ordered_df[ordered_df[,1] < cor_threshold, ]
    return(filtered_df[1, 2])
  }
  
  pcr <- sapply(1:dim(cov_matrix)[1], process_row)
  
  return(pcr)
}
```

```{r}
range_from_function <- compute_pcr(ns_op, cor_threshold)
sum(range_from_function - est_range)
```


```{r}
plot(est_range, type = "l", lty = 2)
lines(range_from_function, col = "red", lty = 3)
```

# References

```{r}
cite_packages(output = "paragraph", out.dir = ".")
```
