---
title: "Non-stationarity"
date: "Created: 05-07-2024. Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    # df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
---

```{r, eval = FALSE, echo = FALSE}
################################################################################
################################################################################
################################################################################
################################################################################
######### DO NOT FORGET TO CHANGE THE TITLE EVERY TIME YOU FIT A MODEL #########
################################################################################
################################################################################
################################################################################
################################################################################
```

```{r xaringanExtra-clipboard, echo = FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa-solid fa-clipboard\" style=\"color: #00008B\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times-circle\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```


```{css, echo = FALSE}
body .main-container {
  max-width: 100% !important;
  width: 100% !important;
}
body {
  max-width: 100% !important;
}

body, td {
   font-size: 16px;
}
code.r{
  font-size: 14px;
}
pre {
  font-size: 14px
}
```


Go back to the [About page](about.html).

Let us set some global options for all code chunks in this document.


```{r}
knitr::opts_chunk$set(
  message = FALSE,    # Disable messages printed by R code chunks
  warning = FALSE,    # Disable warnings printed by R code chunks
  echo = TRUE,        # Show R code within code chunks in output
  include = TRUE,     # Include both R code and its results in output
  eval = TRUE,       # Evaluate R code chunks
  cache = FALSE,       # Enable caching of R code chunks for faster rendering
  fig.align = "center",
  out.width = "100%",
  retina = 2,
  error = TRUE,
  collapse = FALSE
)
rm(list = ls())
set.seed(1982)
```

# Import libraries

```{r}
library(INLA)
library(inlabru)
library(rSPDE)
library(MetricGraph)

library(dplyr)
library(plotly)

library(here)
library(rmarkdown)
library(grateful) # to cite

rm(list = ls()) # Clear the workspace
set.seed(1982) # Set seed for reproducibility
```


<div style="color: blue;">
********
**Press the Show button below to reveal the code.**

********
</div>

```{r}
edges <- logo_lines()
logo_graph <- metric_graph$new(edges = edges)

#logo_graph$plot(vertex_size = 0) + theme_minimal() + theme(text = element_text(family = "Palatino"))

#logo_graph$prune_vertices()
logo_graph$build_mesh(h = 0.05)

# plot mest
logo_graph$plot(mesh = TRUE) + ggtitle("Mesh")

sigma <- 0.1
range <- 10
op <- matern.operators(nu = 1.5, 
                       range = range, 
                       sigma = sigma, 
                       parameterization = "matern",
                       graph = logo_graph)    

u <- as.vector(simulate(op))
logo_graph$plot_function(X = u, vertex_size = 0, plotly = F) + ggtitle("Simulated field")

cov_pos <- 2 * ifelse(logo_graph$mesh$VtE[,2] > 0.5, 
                      1-logo_graph$mesh$VtE[,2], 
                      logo_graph$mesh$VtE[,2])

cov_pos <- u
B.sigma = cbind(0, 1, 0, cov_pos, 0)
B.range = cbind(0, 0, 1,  0, cov_pos)

theta = c(1,1,-0.5,0.5)
#theta = c(0,0,0,0)

# plot range
est_range <- exp(B.range[,-1]%*%theta)
logo_graph$plot_function(X = est_range, vertex_size = 0) + ggtitle("Model for range")

# plot sigma
est_sigma <- exp(B.sigma[,-1]%*%theta)
logo_graph$plot_function(X = est_sigma, vertex_size = 0) + ggtitle("Model for sigma")


rspde_object_ns <- rSPDE::spde.matern.operators(graph = logo_graph,
                                                parameterization = "matern",
                                                B.sigma = B.sigma,
                                                B.range = B.range,
                                                theta = theta,
                                                nu = 0.5)

est_cov_matrix <- rspde_object_ns$covariance_mesh()
est_std_dev <- sqrt(Matrix::diag(est_cov_matrix))

# plot standard deviation from covariance matrix
# logo_graph$plot_function(X = est_std_dev, vertex_size = 0)

# plot standard deviation from precision matrix
library(INLA)
Q <- precision(rspde_object_ns)
est_std_dev_w_inla <- sqrt(diag(INLA::inla.qinv(Q)))
logo_graph$plot_function(X = est_std_dev_w_inla, vertex_size = 0) + ggtitle("Standard deviation")

# plot one row of covariance matrix
rownumber = 300
rowfromcov = est_cov_matrix[rownumber, ]
rowfromQ = solve(Q, replace(numeric(dim(Q)[1]), rownumber, 1))

sum(rowfromcov - rowfromQ)

#logo_graph$plot_function(X = rowfromcov, vertex_size = 0)
#logo_graph$plot_function(X = rowfromQ, vertex_size = 0) + ggtitle("One row of covariance matrix")


# computes distance matrix on the mesh

logo_graph$compute_geodist_mesh()

dist_matrix <- logo_graph$mesh$geo_dist

practical_correlation_range <- 1

rho = rep(NA, dim(est_cov_matrix)[1])
  
for (i in 1:dim(est_cov_matrix)[1]) {
  rowi <- est_cov_matrix[i,]
  sorted <- sort(rowi, decreasing = TRUE, index.return = TRUE)
  index_cor_smaller_pcr <- which(sorted$x < practical_correlation_range)[1]
  pos_dist_matrix <- sorted$ix[index_cor_smaller_pcr]
  rho[i] <- dist_matrix[i, pos_dist_matrix]
}


logo_graph$plot_function(X = rho, vertex_size = 0, plotly = F) + ggtitle("practical correlation range")


xypoints <- logo_graph$mesh$V

sd_df <- data.frame(x = xypoints[,1], y = xypoints[,2], z = est_std_dev_w_inla, .group = 1)
rho_df <- data.frame(x = xypoints[,1], y = xypoints[,2], z = rho, .group = 2)

# (ggplot() +
#   geom_point(data = sd_df, aes(x = x, y = y, color = z), size = 0.5) + 
#   scale_color_viridis_c(option = "D")) |> ggplotly()
# 
# (ggplot() +
#     geom_point(data = rho_df, aes(x = x, y = y, color = z), size = 0.5) + 
#     scale_color_viridis_c(option = "D")) |> ggplotly()


datarep <- rbind(sd_df, rho_df)
group_labels <- c("Standard deviation", "Practical correlation range")

min_x <- min(datarep$x) |> round(2)
max_x <- max(datarep$x) |> round(2)
min_y <- min(datarep$y) |> round(2)
max_y <- max(datarep$y) |> round(2)

# Create a base plot with road network
base_plot <- ggplot() +
  geom_point(data = sd_df, aes(x = x, y = y), color = "black", size = 0.5, shape = 1) +
  scale_x_continuous(labels = function(x) paste0(x), name = "x", breaks = seq(min_x, max_x, by = 2)) +  # Adjust x-axis label and breaks
  scale_y_continuous(labels = function(y) paste0(y), name = "y", breaks = seq(min_y, max_y, by = 2)) +
  theme_minimal()

# Create individual plots for each group and overlay data points
group_plots <- lapply(unique(datarep$.group), function(gr) {
  geom_point(data = subset(datarep, .group == gr), aes(x = x, y = y, color = z), size = 1)  # Adjust x_column and y_column
})

# Combine the base plot and the group plots
combined_plot <- base_plot + 
  facet_wrap(~ .group, ncol = 2, labeller = labeller(.group = function(variable, value) {
    return(group_labels[value])
  })) +  # Specify custom labels for facet_wrap
  group_plots +
  scale_color_gradient(name = "") +
  labs(color = "") +
  scale_color_viridis_c(option = "D")

# Print the combined plot
print(combined_plot)


```


# References

```{r}
cite_packages(output = "paragraph", out.dir = ".")
```
