---
title: "The rol of $\\tau$: Part 4"
date: "Created: 05-07-2024. Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: show # class.source = "fold-hide" to hide code and add a button to show it
    # df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: false
    fig_caption: true
    code_download: true
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
---

```{r xaringanExtra-clipboard, echo = FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa-solid fa-clipboard\" style=\"color: #00008B\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times-circle\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```


```{css, echo = FALSE}
body .main-container {
  max-width: 100% !important;
  width: 100% !important;
}
body {
  max-width: 100% !important;
}

body, td {
   font-size: 16px;
}
code.r{
  font-size: 14px;
}
pre {
  font-size: 14px
}
.custom-box {
  background-color: #f5f7fa; /* Light grey-blue background */
  border-color: #e1e8ed; /* Light border color */
  color: #2c3e50; /* Dark text color */
  padding: 15px; /* Padding inside the box */
  border-radius: 5px; /* Rounded corners */
  margin-bottom: 20px; /* Spacing below the box */
}
.caption {
  margin: auto;
  text-align: center;
  margin-bottom: 20px; /* Spacing below the box */
}
```


Below we set some global options for all code chunks in this document.


```{r}
# Set seed for reproducibility
set.seed(593) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}
# Define the function to truncate a number to two decimal places
truncate_to_two <- function(x) {
  floor(x * 100) / 100
}
```


Below we load the necessary libraries and define the auxiliary functions.

```{r}
library(rSPDE)
library(MetricGraph)

library(dplyr)
library(plotly)
library(scales)
library(patchwork)
library(tidyr)

library(here)
library(rmarkdown)
# Cite all loaded packages
library(grateful)
```



Let's build a small graph to illustrate the effect of $\tau$ on the graph.

```{r}
A <- 1
edge1 <- rbind(c(A,0),c(0,0))
edge2 <- rbind(c(0,A),c(0,0))
edge3 <- rbind(c(-A,A),c(-A/2,A))
theta <- seq(from = pi,to = 2*pi,length.out = 50)
edge4 <- cbind(-A + A/2*sin(theta), A/2 + A/2*cos(theta))
edge5 <- rbind(c(0,A),c(A/2,A))
edge6 <- rbind(c(0,0),c(-A,0))
edge7 <- rbind(c(-A,A),c(0,0))
edge8 <- rbind(c(A,A),c(0,0))
edge9 <- rbind(c(-A/2,A),c(0,A))
edge10 <- rbind(c(A/2,A),c(A,A))
edge11 <- rbind(c(-A/2,A),c(0,0))
edge12 <- rbind(c(A/2,A),c(0,0))
edges <- list(edge1, edge2, edge3, edge4, edge5, edge6, edge7, edge8, edge9, edge10, edge11, edge12)
```

```{r}
graph <- metric_graph$new(edges = edges)
graph$build_mesh(h = 0.1, continuous = TRUE)
edge_number <- graph$mesh$VtE
XY_graph <- graph$mesh$V
```


```{r, fig.cap = captioner("Edge directions.")}
graph$plot(direction = TRUE) + 
  theme_minimal() + 
  theme(text = element_text(family = "Palatino"))
```


```{r}
sigma1 <- 0.1
sigma2 <- 5
range1 <- 0.05
range2 <- 0.4
nu1 <- 0.1
nu2 <- 5.5
```


:::: {style="display: grid; grid-template-columns: 300px 300px 300px 300px; grid-column-gap: 1px;"}

::: {}


```{r, out.width = "100%"}
sigma <- sigma1
range <- range1
nu <- nu1
op <- matern.operators(nu = nu, range = range, sigma = sigma, 
                         parameterization = "matern",
                         m = 2, graph = graph)                     

cov <- op$covariance_mesh()
est_sigma <- sqrt(Matrix::diag(cov))

graph$plot_function(X = est_sigma, vertex_size = 0, plotly = TRUE, line_color = "darkgreen", line_width = 3) %>%  
  config(mathjax = 'cdn') %>% 
  layout(title = TeX("\\sigma"), 
scene = list(
           aspectratio = list(x = 1/6, y = 1/3, z = 1/3),
           camera = list(
      eye = list(x = 1, y = 0, z = 1/2),  # Adjust the viewpoint
      center = list(x = 0, y = 0, z = 0))))
```


:::

::: {}


```{r, out.width = "100%"}
sigma <- sigma1
range <- range1
nu <- nu2
op <- matern.operators(nu = nu, range = range, sigma = sigma,
                         parameterization = "matern",
                         m = 2, graph = graph)

cov <- op$covariance_mesh()
est_sigma <- sqrt(Matrix::diag(cov))

graph$plot_function(X = est_sigma, vertex_size = 0, plotly = TRUE, line_color = "darkgreen", line_width = 3) %>%
  config(mathjax = 'cdn') %>% 
  layout(title = TeX("\\sigma"), 
scene = list(
           aspectratio = list(x = 1/6, y = 1/3, z = 1/3),
           camera = list(
      eye = list(x = 1, y = 0, z = 1/2),  # Adjust the viewpoint
      center = list(x = 0, y = 0, z = 0))))
```

:::

::: {}

```{r, out.width = "100%"}
sigma <- sigma1
range <- range2
nu <- nu1
op <- matern.operators(nu = nu, range = range, sigma = sigma,
                         parameterization = "matern",
                         m = 2, graph = graph)

cov <- op$covariance_mesh()
est_sigma <- sqrt(Matrix::diag(cov))

graph$plot_function(X = est_sigma, vertex_size = 0, plotly = TRUE, line_color = "darkgreen", line_width = 3) %>%
  config(mathjax = 'cdn') %>% 
  layout(title = TeX("\\sigma"), 
scene = list(
           aspectratio = list(x = 1/6, y = 1/3, z = 1/3),
           camera = list(
      eye = list(x = 1, y = 0, z = 1/2),  # Adjust the viewpoint
      center = list(x = 0, y = 0, z = 0))))
```


:::

::: {}


```{r, out.width = "100%"}
sigma <- sigma1
range <- range2
nu <- nu2
op <- matern.operators(nu = nu, range = range, sigma = sigma,
                         parameterization = "matern",
                         m = 2, graph = graph)

cov <- op$covariance_mesh()
est_sigma <- sqrt(Matrix::diag(cov))

graph$plot_function(X = est_sigma, vertex_size = 0, plotly = TRUE, line_color = "darkgreen", line_width = 3) %>%
  config(mathjax = 'cdn') %>% 
  layout(title = TeX("\\sigma"), 
scene = list(
           aspectratio = list(x = 1/6, y = 1/3, z = 1/3),
           camera = list(
      eye = list(x = 1, y = 0, z = 1/2),  # Adjust the viewpoint
      center = list(x = 0, y = 0, z = 0))))
```


:::

::::



:::: {style="display: grid; grid-template-columns: 300px 300px 300px 300px; grid-column-gap: 1px;"}

::: {}


```{r, out.width = "100%"}
sigma <- sigma2
range <- range1
nu <- nu1
op <- matern.operators(nu = nu, range = range, sigma = sigma,
                         parameterization = "matern",
                         m = 2, graph = graph)

cov <- op$covariance_mesh()
est_sigma <- sqrt(Matrix::diag(cov))

graph$plot_function(X = est_sigma, vertex_size = 0, plotly = TRUE, line_color = "darkgreen", line_width = 3) %>%
  config(mathjax = 'cdn') %>% 
  layout(title = TeX("\\sigma"), 
scene = list(
           aspectratio = list(x = 1/6, y = 1/3, z = 1/3),
           camera = list(
      eye = list(x = 1, y = 0, z = 1/2),  # Adjust the viewpoint
      center = list(x = 0, y = 0, z = 0))))
```


:::

::: {}


```{r, out.width = "100%"}
sigma <- sigma2
range <- range1
nu <- nu2
op <- matern.operators(nu = nu, range = range, sigma = sigma,
                         parameterization = "matern",
                         m = 2, graph = graph)

cov <- op$covariance_mesh()
est_sigma <- sqrt(Matrix::diag(cov))

graph$plot_function(X = est_sigma, vertex_size = 0, plotly = TRUE, line_color = "darkgreen", line_width = 3) %>%
  config(mathjax = 'cdn') %>% 
  layout(title = TeX("\\sigma"), 
scene = list(
           aspectratio = list(x = 1/6, y = 1/3, z = 1/3),
           camera = list(
      eye = list(x = 1, y = 0, z = 1/2),  # Adjust the viewpoint
      center = list(x = 0, y = 0, z = 0))))
```

:::

::: {}

```{r, out.width = "100%"}
sigma <- sigma2
range <- range2
nu <- nu1
op <- matern.operators(nu = nu, range = range, sigma = sigma,
                         parameterization = "matern",
                         m = 2, graph = graph)

cov <- op$covariance_mesh()
est_sigma <- sqrt(Matrix::diag(cov))

graph$plot_function(X = est_sigma, vertex_size = 0, plotly = TRUE, line_color = "darkgreen", line_width = 3) %>%
  config(mathjax = 'cdn') %>% 
  layout(title = TeX("\\sigma"), 
scene = list(
           aspectratio = list(x = 1/6, y = 1/3, z = 1/3),
           camera = list(
      eye = list(x = 1, y = 0, z = 1/2),  # Adjust the viewpoint
      center = list(x = 0, y = 0, z = 0))))
```


:::

::: {}


```{r, out.width = "100%"}
sigma <- sigma2
range <- range2
nu <- nu2
op <- matern.operators(nu = nu, range = range, sigma = sigma,
                         parameterization = "matern",
                         m = 2, graph = graph)

cov <- op$covariance_mesh()
est_sigma <- sqrt(Matrix::diag(cov))

graph$plot_function(X = est_sigma, vertex_size = 0, plotly = TRUE, line_color = "darkgreen", line_width = 3) %>%
  config(mathjax = 'cdn') %>% 
  layout(title = TeX("\\sigma"), 
scene = list(
           aspectratio = list(x = 1/6, y = 1/3, z = 1/3),
           camera = list(
      eye = list(x = 1, y = 0, z = 1/2),  # Adjust the viewpoint
      center = list(x = 0, y = 0, z = 0))))
```


:::

::::


# References

```{r}
cite_packages(output = "paragraph", out.dir = ".")
```

