---
title: "Description of files and folders in `data_files` directory"
output:
  html_document:
    number_sections: true
    highlight: textmate
    theme: flatly
    css: ../style.css
---

Here is a short description of the files and folders in the [`data_files`](https://github.com/leninrafaelrierasegura/GWMF/tree/main/data_files) directory.

1. [**`Error_interval_DEF.RData`**](https://github.com/leninrafaelrierasegura/GWMF/blob/main/data_files/Error_interval_DEF.RData)

This file was created in [`numerical_error.html`](../numerical_error.html).

2. [**`Error_circle_DEF.RData`**](https://github.com/leninrafaelrierasegura/GWMF/blob/main/data_files/Error_circle_DEF.RData)

This file was created in [`numerical_error.html`](../numerical_error.html).

3. [**`Error_tadpole_DEF_rho0.1.RData`**](https://github.com/leninrafaelrierasegura/GWMF/blob/main/data_files/Error_tadpole_DEF_rho0.1.RData)

This file was created in [`numerical_error.html`](../numerical_error.html).

4. [**`Error_tadpole_DEF_rho0.5.RData`**](https://github.com/leninrafaelrierasegura/GWMF/blob/main/data_files/Error_tadpole_DEF_rho0.5.RData)

This file was created in [`numerical_error.html`](../numerical_error.html).

5. [**`Error_tadpole_DEF_rho1.RData`**](https://github.com/leninrafaelrierasegura/GWMF/blob/main/data_files/Error_tadpole_DEF_rho1.RData)

This file was created in [`numerical_error.html`](../numerical_error.html).

6. [**`Error_tadpole_DEF_rho2.RData`**](https://github.com/leninrafaelrierasegura/GWMF/blob/main/data_files/Error_tadpole_DEF_rho2.RData)

This file was created in [`numerical_error.html`](../numerical_error.html).


7. [**`conv_rates_new.png`**](https://github.com/leninrafaelrierasegura/GWMF/blob/main/data_files/conv_rates_new.png)

This file was created in [`convergence_rates.html`](../convergence_rates.html).


8. [**`data.pems/`**](https://github.com/leninrafaelrierasegura/GWMF/tree/main/data_files/data.pems)

This folder was downloaded from this [GitHub repository](https://github.com/davidbolin/MetricGraph/tree/7f4c90171c40b9bf7ea29e9b048c93d88477c5d1/examples/data.pems) and contains the data used in the [`pems_repl1.html`](../pems_repl1.html) vignette.  


